grep: .: Is a directory
grep: ./multiqc: Is a directory
grep: ./multiqc/utils: Is a directory
grep: ./multiqc/plots: Is a directory
grep: ./multiqc/templates: Is a directory
grep: ./multiqc/templates/default: Is a directory
grep: ./multiqc/templates/default/assets: Is a directory
grep: ./multiqc/templates/default/assets/css: Is a directory
grep: ./multiqc/templates/default/assets/img: Is a directory
grep: ./multiqc/templates/default/assets/js: Is a directory
grep: ./multiqc/templates/default/assets/js/packages: Is a directory
grep: ./multiqc/templates/default/assets/fonts: Is a directory
grep: ./multiqc/templates/simple: Is a directory
grep: ./multiqc/templates/default_dev: Is a directory
grep: ./multiqc/templates/geo: Is a directory
grep: ./multiqc/templates/geo/assets: Is a directory
grep: ./multiqc/templates/geo/assets/css: Is a directory
grep: ./multiqc/templates/geo/assets/img: Is a directory
grep: ./multiqc/modules: Is a directory
grep: ./multiqc/modules/snpeff: Is a directory
grep: ./multiqc/modules/qualimap: Is a directory
grep: ./multiqc/modules/methylQA: Is a directory
grep: ./multiqc/modules/fastqc: Is a directory
grep: ./multiqc/modules/fastqc/assets: Is a directory
grep: ./multiqc/modules/fastqc/assets/css: Is a directory
grep: ./multiqc/modules/fastqc/assets/js: Is a directory
grep: ./multiqc/modules/samblaster: Is a directory
grep: ./multiqc/modules/samtools: Is a directory
grep: ./multiqc/modules/tophat: Is a directory
grep: ./multiqc/modules/star: Is a directory
grep: ./multiqc/modules/hicup: Is a directory
grep: ./multiqc/modules/bamtools: Is a directory
grep: ./multiqc/modules/preseq: Is a directory
grep: ./multiqc/modules/picard: Is a directory
grep: ./multiqc/modules/featureCounts: Is a directory
grep: ./multiqc/modules/bowtie2: Is a directory
grep: ./multiqc/modules/ssds: Is a directory
grep: ./multiqc/modules/salmon: Is a directory
grep: ./multiqc/modules/skewer: Is a directory
grep: ./multiqc/modules/cutadapt: Is a directory
grep: ./multiqc/modules/trimmomatic: Is a directory
grep: ./multiqc/modules/bismark: Is a directory
grep: ./multiqc/modules/fastq_screen: Is a directory
grep: ./multiqc/modules/kallisto: Is a directory
grep: ./multiqc/modules/bowtie1: Is a directory
grep: ./multiqc/modules/rseqc: Is a directory
grep: ./dist: Is a directory
grep: ./buildOLD: Is a directory
grep: ./buildOLD/scripts-2.7: Is a directory
grep: ./buildOLD/bdist.linux-x86_64: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/utils: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/plots: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/default: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/default/assets: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/default/assets/css: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/default/assets/img: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/default/assets/js: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/default/assets/js/packages: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/default/assets/fonts: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/simple: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/default_dev: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/geo: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/geo/assets: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/geo/assets/css: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/templates/geo/assets/img: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/snpeff: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/qualimap: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/methylQA: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/fastqc: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/fastqc/assets: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/fastqc/assets/css: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/fastqc/assets/js: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/samblaster: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/samtools: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/tophat: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/star: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/hicup: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/bamtools: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/preseq: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/picard: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/featureCounts: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/bowtie2: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/ssds: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/salmon: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/skewer: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/cutadapt: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/trimmomatic: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/bismark: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/fastq_screen: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/kallisto: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/bowtie1: Is a directory
grep: ./buildOLD/lib.linux-x86_64-2.7/multiqc/modules/rseqc: Is a directory
grep: ./multiqc.egg-info: Is a directory
grep: ./build: Is a directory
grep: ./build/scripts-2.7: Is a directory
grep: ./build/bdist.linux-x86_64: Is a directory
grep: ./build/lib.linux-x86_64-2.7: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/utils: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/plots: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/default: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/default/assets: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/default/assets/css: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/default/assets/img: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/default/assets/js: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/default/assets/js/packages: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/default/assets/fonts: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/simple: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/default_dev: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/geo: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/geo/assets: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/geo/assets/css: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/templates/geo/assets/img: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/snpeff: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/qualimap: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/methylQA: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/fastqc: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/fastqc/assets: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/fastqc/assets/css: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/fastqc/assets/js: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/samblaster: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/samtools: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/tophat: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/star: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/hicup: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/bamtools: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/preseq: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/picard: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/featureCounts: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/bowtie2: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/ssds: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/salmon: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/skewer: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/cutadapt: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/trimmomatic: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/bismark: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/fastq_screen: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/kallisto: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/bowtie1: Is a directory
grep: ./build/lib.linux-x86_64-2.7/multiqc/modules/rseqc: Is a directory
grep: ./scripts: Is a directory
grep: ./.git: Is a directory
grep: ./.git/info: Is a directory
grep: ./.git/hooks: Is a directory
grep: ./.git/logs: Is a directory
grep: ./.git/logs/refs: Is a directory
grep: ./.git/logs/refs/heads: Is a directory
grep: ./.git/logs/refs/remotes: Is a directory
grep: ./.git/logs/refs/remotes/origin: Is a directory
grep: ./.git/refs: Is a directory
grep: ./.git/refs/tags: Is a directory
grep: ./.git/refs/heads: Is a directory
grep: ./.git/refs/remotes: Is a directory
grep: ./.git/refs/remotes/origin: Is a directory
grep: ./.git/branches: Is a directory
grep: ./.git/objects: Is a directory
grep: ./.git/objects/pack: Is a directory
grep: ./.git/objects/info: Is a directory
grep: ./.github: Is a directory
grep: ./docs: Is a directory
grep: ./docs/images: Is a directory
grep: ./docs/modules: Is a directory
