#######################################
# Example MultiQC Configuration File
#######################################

# This file can be saved either in the MultiQC installation
# directory, or as ~/.multiqc_config.yaml

# Configuration settings are taken from the following locations, in order:
# - Hardcoded in MultiQC (multiqc/utils/config.py)
# - <installation_dir>/multiqc_config.yaml
# - ~/.multiqc_config.yaml
# - Command line options

# Note that all of the values below are set to the MultiQC defaults.
# It's recommended that you delete any that you don't need.

---
# Title to use for the report.
title: None

# Prepend sample names with their directory. Useful if analysing the
# sample samples with different parameters.
prepend_dirs: False

# Default output filenames
output_fn_name: multiqc_report.html
data_dir_name: multiqc_data

# Whether to create the parsed data directory in addition to the report
make_data_dir: True

# Cleaning options for sample names. Typically, sample names are detected
# from an input filename. If any of these strings are found, they and any
# text to their right will be discarded.
# For example - file1.fq.gz_trimmed.bam_deduplicated_fastqc.zip
# would be cleaned to 'file1'
# Two options here - fn_clean_exts will replace the defaults,
# extra_fn_clean_exts will append to the defaults
extra_fn_clean_exts:
    - .gz
    - .fastq
    - .fq
    - .bam
    - .sam
    - .sra
    - _tophat
    - _star_aligned
    - _fastqc
    - type: replace
      pattern: '.sorted'
    - type: regex
      pattern: '^Sample_\d+'

# Ignore these files when searching for logs
fn_ignore_files:
    - .DS_Store

# Ignore files larger than this when searcing for logs (bytes)
log_filesize_limit: 1000000

# MultiQC can save a DEBUG log message when it can't read a file. These are disabled
# by default as they can be very verbose. Enable by setting to True for debugging.
report_readerrors: False

# Opt-out of remotely checking that you're running the latest version
no_version_check: True

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False          # Try to use only flat image graphs
plots_force_interactive: False   # Try to use only interactive javascript graphs
plots_flat_numseries: 100        # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 50       # If interactive, don't plot on load if > this number of datasets
genstats_beeswarm_numseries: 100  # Swap the General Statistics table for a beeswarm plot above this

# Overwrite module filename search patterns. See multiqc/utils/search_patterns.yaml
# for the defaults. Remove a default by setting it to None.
sp:
    bismark:
        meth_extract:
            contents: Bismark Extractor Version



